name: Build, Version, and Release

on:
  push:
    branches:
      - main  # Trigger on main branch

permissions:
  contents: write  # Required for tagging and creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Up Git User
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Run Prepare Script for Environment Setup
      run: |
        bash prepare.sh

    - name: Run Build Script
      run: |
        bash build.sh

    - name: Run Version Increment Script (Only if Build Succeeds)
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Increment version, create and push a new tag
        bash version-increment.sh
        # Push the new tag to GitHub


    - name: Create GitHub Release
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(grep -oP 'version=\K.*' library.properties)
        release_name="Release v$version"
        release_body="Automatic release for version v$version"
        # Create the release
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\":\"v$version\",\"name\":\"$release_name\",\"body\":\"$release_body\",\"draft\":false,\"prerelease\":false}" \
          https://api.github.com/repos/${{ github.repository }}/releases
